// This file was automatically generated by genheaders.sh
// Do NOT edit it manually

#ifndef COMPONENTS_HPP
#define COMPONENTS_HPP

#include "components/attack_component.hpp"
#include "components/base_component.hpp"
#include "components/health_component.hpp"
#include "components/movement_component.hpp"
#include "components/position_component.hpp"
#include "components/team_component.hpp"

#endif // COMPONENTS_HPP
