// THIS FILE WAS AUTOMATICALLY GENERATED BY genheaders.sh
// DO NOT EDIT MANUALLY

#ifndef MESSAGES_HPP
#define MESSAGES_HPP

#include "messages/base_message.hpp"
#include "messages/death_message.hpp"
#include "messages/health_message.hpp"
#include "messages/position_changed_message.hpp"

#endif // MESSAGES_HPP