// This file was automatically generated by genheaders.sh
// Do NOT edit it manually

#ifndef SYSTEMS_HPP
#define SYSTEMS_HPP

#include "systems/base_system.hpp"
#include "systems/health_system.hpp"
#include "systems/movement_system.hpp"
#include "systems/reproduction_system.hpp"

#endif // SYSTEMS_HPP
