// THIS FILE WAS AUTOMATICALLY GENERATED BY genheaders.sh
// DO NOT EDIT MANUALLY

#ifndef COMPONENTS_HPP
#define COMPONENTS_HPP

#include "components/team_component.hpp"
#include "components/position_component.hpp"
#include "components/health_component.hpp"
#include "components/base_component.hpp"

#endif // COMPONENTS_HPP