// THIS FILE WAS AUTOMATICALLY GENERATED BY genheaders.sh
// DO NOT EDIT MANUALLY

#ifndef SYSTEMS_HPP
#define SYSTEMS_HPP

#include "systems/base_system.hpp"
#include "systems/health_system.hpp"

#endif // SYSTEMS_HPP