// This file was automatically generated by genheaders.sh
// Do NOT edit it manually

#ifndef COMPONENTS_HPP
#define COMPONENTS_HPP

#include "components/position_manager.hpp"

#endif // COMPONENTS_HPP
