// This file was automatically generated by genheaders.sh
// Do NOT edit it manually

#ifndef COMPONENTS_HPP
#define COMPONENTS_HPP

#include "components/attack.hpp"
#include "components/health.hpp"
#include "components/movement.hpp"
#include "components/position.hpp"

#endif // COMPONENTS_HPP
