// This file was automatically generated by genheaders.sh
// Do NOT edit it manually

#ifndef COMPONENTS_HPP
#define COMPONENTS_HPP

#include "components/health.hpp"
#include "components/movement.hpp"
#include "components/position.hpp"
#include "components/reproduction.hpp"
#include "components/species.hpp"

#endif // COMPONENTS_HPP
