// This file was automatically generated by genheaders.sh
// Do NOT edit it manually

#ifndef SYSTEMS_HPP
#define SYSTEMS_HPP

#include "systems/health.hpp"
#include "systems/movement.hpp"
#include "systems/reproduction.hpp"

#endif // SYSTEMS_HPP
