// This file was automatically generated by genheaders.sh
// Do NOT edit it manually

#ifndef COMMON_HPP
#define COMMON_HPP

#include "common/log.hpp"
#include "common/time.hpp"

#endif // COMMON_HPP
