// This file was automatically generated by genheaders.sh
// Do NOT edit it manually

#ifndef ECS_OO_HPP
#define ECS_OO_HPP

#include "ecs_oo/components.hpp"
#include "ecs_oo/entity.hpp"
#include "ecs_oo/id_generator.hpp"
#include "ecs_oo/systems.hpp"
#include "ecs_oo/world.hpp"

#endif // ECS_OO_HPP
