#!/bin/bash

function process() {
	local dir=$1
	local bn=`basename $dir`
	for d in `find $dir -maxdepth 1 -type d ! -name $bn`; do
		if [[ "$d" != *"glm"* ]]; then
			process $d
		fi
	done

	local out="$dir.hpp"
	local def="`echo $bn | tr /a-z/ /A-Z/`_HPP"
	echo -e "// This file was automatically generated by genheaders.sh" > $out
	echo -e "// Do NOT edit it manually\n" >> $out
	echo -e "#ifndef $def\n#define $def\n" >> $out
	for f in `ls $dir | grep .hpp`; do
		echo -e "#include \"$bn/$f\"" >> $out
	done
	echo -e "\n#endif // $def" >> $out
}

process include
rm -f include.hpp
