#!/bin/bash

for d in `find include/ecs_oo -type d ! -name ecs_oo` ; do
	b=`basename $d`
	u=`echo -n $b | tr /a-z/ /A-Z/`
	echo -e "// THIS FILE WAS AUTOMATICALLY GENERATED BY genheaders.sh" > $d.hpp
	echo -e "// DO NOT EDIT MANUALLY\n" >> $d.hpp
	echo -e "#ifndef ${u}_HPP\n#define ${u}_HPP\n" >> $d.hpp
	for f in `find $d -name '*.hpp'`; do
		echo -e "#include \"$b/`basename $f`\"" >> $d.hpp;
	done
	echo -ne "\n#endif // ${u}_HPP" >> $d.hpp;
done

echo -e "// THIS FILE WAS AUTOMATICALLY GENERATED BY genheaders.sh" > include/ecs_oo.hpp
echo -e "// DO NOT EDIT MANUALLY\n" >> include/ecs_oo.hpp
echo -e "#ifndef OOD_ECS_HPP\n#define OOD_ECS_HPP\n" >> include/ecs_oo.hpp
for f in `cd include && find ecs_oo -maxdepth 1 -name '*.hpp'` ; do
	echo -e "#include \"$f\"" >> include/ecs_oo.hpp;
done
echo -e "\n#endif // OOD_ECS_HPP" >> include/ecs_oo.hpp
